import Head from 'next/head';
import Home from '@/components/Home';
import { GetStaticPropsContext } from 'next';
import { API_ENDPOINTS } from '@/lib/constant';
import TableOfContent from '@/types/TableOfContent';

export async function getStaticProps(context: GetStaticPropsContext) 
{
    const res = await fetch(API_ENDPOINTS.TableOfContent)
    const tableOfContent = (await res.json())

    return {
        props: {
            tableOfContent
        },
        revalidate: 2
    };
}

export default function Page({ tableOfContent }:{ tableOfContent: TableOfContent }) 
{
    return (
        <>
            <Head>
                <title>The Palestinian Side</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Home 
                    tableOfContent={tableOfContent}
                />
            </main>
        </>
    );
}
