import Head from 'next/head';
import Home from '@/components/Home';
import TableOfContent from '@/types/TableOfContent';

export default function Page({ tableOfContent }:{ tableOfContent: TableOfContent }) 
{
    return (
        <>
            <Head>
                <title>The Palestinian Side</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Home 
                    tableOfContent={tableOfContent}
                    />
            </main>
        </>
    );
}

import { GetStaticPropsContext } from 'next';
import { CONTENT_DIR } from '@/lib/constant';
import { readdirSync } from 'fs';

export async function getStaticProps(context: GetStaticPropsContext) 
{
    const tableOfContent =  readdirSync(CONTENT_DIR).map(name=> `${name.replace(/^(.*?)\.[^.]+$/, '$1')}`)
    
    return {
        props: {
            tableOfContent
        },
        revalidate: 2
    };
}
