import Head from 'next/head';
import Home from '@/components/Home';
import TableOfContent from '@/types/TableOfContent';

export default function Page({ tableOfContent }:{ tableOfContent: TableOfContent }) 
{
    return (
        <>
            <Head>
                <title>The Palestinian Side</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Home 
                    tableOfContent={tableOfContent}
                />
            </main>
        </>
    );
}

import { GetStaticPropsContext } from 'next';
import { getTableOfContent } from '@/lib/content';

export async function getStaticProps(context: GetStaticPropsContext) 
{
    const tableOfContent =  getTableOfContent()
    
    return {
        props: { tableOfContent }, revalidate: 2
    };
}
