import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'

// components
import Header from '@/components/Header'
import clsx from 'clsx'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className={clsx('flex w-full')}>
          <div
            className={clsx('p-2 w-full max-w-[1420px] mx-auto', 'flex-col')}>
            <MarkDownLayout>{children}</MarkDownLayout>
          </div>
        </main>
      </body>
    </html>
  )
}

const MarkDownLayout = ({ children }: { children: ReactNode }) => {
  return (
    <div className={clsx('p-4 flex flex-col bg-slate-200 rounded-md')}>
      {children}
    </div>
  )
}
