import ContentLayout from "@/Layout/ContentLayout";
import MarkDownContent from "@/components/MarkDownContent";
import Head from "next/head";

export default function Page ({ content } : { content: string}) 
{
    useFirebaseAnalyticsReport(FIREBASE_ANALYTICS_EVENTS.content)
    
    return <>
        <Head>
            <title>The Palestinian Side</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <ContentLayout p={2}>
                <MarkDownContent>
                    {content}
                </MarkDownContent>
            </ContentLayout>
        </main>
    </>
}

import { GetStaticPropsContext } from "next";
import  { getTableOfContent, getContentOfFile } from "@/lib/content";
import { FIREBASE_ANALYTICS_EVENTS, useFirebaseAnalyticsReport } from "@/lib/firebase_analytics";

export async function getStaticPaths () 
{
    const tableOfContent = getTableOfContent();
    console.log(tableOfContent)
    const paths = tableOfContent.map((p: any) => ({ params: { id: p } }))
    return { paths, fallback: true }
}

export async function getStaticProps(context: GetStaticPropsContext)
{
    const { id } = context.params as { id: string}
    const fileContent = getContentOfFile(id) 

    return {
        props: {
            content: fileContent
        },
        revalidate: 5
    }
}

