import ContentLayout from "@/Layout/ContentLayout";
import MarkDownContent from "@/components/MarkDownContent";
import { API_ENDPOINTS } from "@/lib/constant"
import { GetStaticPropsContext } from "next"
import Head from "next/head"

export async function getStaticPaths () 
{
    const res = await fetch(API_ENDPOINTS.TableOfContent);
    const paths = (await res.json()).map((p: string) => ({ params: { id: p } }))
    
    return { paths, fallback: true }
}

export async function getStaticProps(context: GetStaticPropsContext)
{
    const { id } = context.params as { id: string}
    const res = await fetch(`${API_ENDPOINTS.Content}?id=${encodeURIComponent(id)}`)
    const { content } = await res.json()
    
    return {
        props: {
            content
        },
        revalidate: 5
    }
}

export default function Page ({ content } : { content: string}) 
{
    return <>
        <Head>
            <title>The Palestinian Side</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <ContentLayout p={2}>
                <MarkDownContent>
                    {content}
                </MarkDownContent>
            </ContentLayout>
        </main>
    </>
}
